on: [push]

jobs:
  inspection:
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2021.3.16f1-linux-il2cpp-1
    name: Inspection
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-lint-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: Library-lint-

      - name: Solution generation
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android
          versioning: None
          buildMethod: "Packages.Rider.Editor.RiderScriptEditor.SyncSolution"
          manualExit: false

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore Dependencies
        run: dotnet restore workspace.sln
      - name: Install resharper unity plugin
        run: |
          nuget install -source https://resharper-plugins.jetbrains.com/api/v2/ -source https://nuget.org/api/v2/ JetBrains.Unity
      - name: Upload project
        uses: actions/upload-artifact@v4
        with:
          name: project
          path: ./
      - name: Upload engine dlls
        uses: actions/upload-artifact@v4
        with:
          name: engine
          path: /opt/unity/Editor/Data/Managed/UnityEngine/
      - name: Upload dontet dlls
        uses: actions/upload-artifact@v4
        with:
          name: dotnet
          path: /opt/unity/Editor/Data/NetStandard/compat/
      - name: Inspect code
        uses: muno92/resharper_inspectcode@v1
        with:
          solutionPath: ./workspace.sln